### ISSUE TITLE
Package tidy up

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/snowplow#84]
Copied from https://github.com/fishtown-analytics/segment/issues/42

### Repo checklist:
- [x] A license
- [x] Issue and PR templates (as of #79)
- [x] A [codeowner](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) (as of #79)
- [x] The hub URL listed on the repo
- [x] ~If relevant, a note in the README saying this package is not actively supported~
- [x] Installation instructions, including:
    - Link to packages docs
    - Variables that need to be included in the `dbt_project.yml` file
    - Listed database support
- [x] A link to our package [contribution guide](https://discourse.getdbt.com/t/contributing-to-a-dbt-package/657) (as of #79)
- [x] A `require-dbt-version` parameter in the `dbt_project.yml`
- [x] Models are documented
- [x] Macros are documented (as of #79)
- [x] Integration tests
- [x] Move model logic intro model files, rather than entirely in adapter macros
- [x] A Zap to the #package-releases channel in dbt Slack
